# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: index
  unique: true
  elements: [article]
  autogenerate: [article]

- name: contact
  cache: false
  unique: true
  elements: [headline, contactform, text]
  autogenerate: [headline, contactform]

  - name: page
  cache: false
  unique: false
  elements: [headline, text]
  autogenerate: [headline]
